### PR TITLE
Update schema.json

### PR DESCRIPTION
**Pull request by MiguelLCorb**
Adding three parameters, totalEnergy, totalDailyEnergy and refInverterDevice, commonly used in in-house green energy production systems.  Adding the greenEnergyProduction tag.

### CODE REVIEW

**Review by albertoabellagarcia — CHANGES_REQUESTED** [review]
Agree on the tag, but if you add an attribute to the schema we need an payload using it

**Comment by albertoabellagarcia** [comment]
Will you provide the example? Otherwise we should close the issue and to reopen when available.

**Comment by MiguelLCorb** [comment]
Adding a screenshot of an active inverterMeasurement entity on our platform, showing two of the proposed new attributes. Ammended the schema to take out totalDailyEnergy, which I've been told was proposed but has not been ultimately implemented. 

Badajoz Provincial Council - inverterMeasurement sample

**Review by albertoabellagarcia — APPROVED** [review]

**Comment by albertoabellagarcia** [comment]
The data model has been extended. You can appear in the [contributors file](https://github.com/smart-data-models/dataModel.OCF/blob/master/CONTRIBUTORS.yaml). 
Make a PR with your data

**Pull request merged**
